#!/bin/bash
# Create a temporary directory to work in
#
# mkdir temp
#
# cd temp
#
#
#
# # Copy the directory structure to the temporary directory
#
# cp -r "$CURRENT_DIR" .
#
#
#
# # Find all files with a .js extension and delete them
#
# find . -type f -name '*.js' -exec rm {} \;
#
#
#
# # Copy the directory structure back to the original location
#
# cp -r . "$CURRENT_DIR"
#
#
#
# # Clean up the temporary directory
#
# cd ..
#
# rm -rf temp
